version: '3.8'

services:
  flask_CPR_web_app:
    build:
      context: .
      dockerfile: Dockerfile-flask-yolo
    shm_size: '20gb'
    environment:
      - DISPLAY=${DISPLAY} #DISPLAY=172.17.0.1:0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /home/watanabe/research/Docker-composes/flask_CPR_web_app:/Container
      - /home/watanabe/research/CPR-dataset:/CPR-dataset
      - /media/watanabe/SPD-2TB/CPR-output:/CPR-output
      - /media/watanabe/SPD-2TB/CPR_video:/CPR_video
      - /tmp/.X11-unix:/tmp/.X11-unix
    image: image-flask-yolo
    container_name: cpr-flask-yolo
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    #network_mode: "host"
    runtime: nvidia
    working_dir: /Container
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
            cpus: '6.5'
            memory: 30G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [utility, compute, video]

volumes:
  data:
    external: true
