#FROM  nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
#docker-compose.ymlで動く
FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04

ENV NOTO_DIR /usr/share/fonts/opentype/notosans
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64/7fa2af80.pub
RUN rm -rf /var/lib/apt/lists/*

# base
RUN apt update \
    && apt install -y \
    wget \
    unzip \
    git \
    sudo \
    libgl1-mesa-dev \
    libx11-dev \
    curl \
    x11-apps

RUN apt update && sudo apt-get install -y ffmpeg libopencv-dev libgtk-3-dev \
    libdc1394-22 libdc1394-22-dev libjpeg-dev libpng-dev libtiff5-dev \
    libavcodec-dev libavformat-dev libswscale-dev libxine2-dev libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev libv4l-dev libtbb-dev qtbase5-dev libfaac-dev \
    libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev \
    libvorbis-dev libxvidcore-dev x264 v4l-utils

# Python version
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update && sudo apt install -y python3.10
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
RUN update-alternatives --config python3
RUN apt update && sudo apt install -y python3-pip python3.10-distutils python3.10-tk
RUN apt update && sudo apt-get install -y build-essential cmake

# Python library 
COPY requirements-flask.txt /tmp/
COPY .bashrc /root/.bashrc
RUN ["/bin/bash", "-c", " source /root/.bashrc"]
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
RUN pip3 install --no-cache-dir -U pip setuptools wheel \
    && pip3 install --no-cache-dir -r /tmp/requirements-flask.txt

RUN apt install -y protobuf-compiler
RUN apt update && sudo apt install -y curl gnupg
RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
RUN mv bazel.gpg /etc/apt/trusted.gpg.d/
RUN echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
RUN apt update && sudo apt install -y bazel=5.0.0